### ISSUE TITLE
OCR detection issue

### ISSUE THREAD

**Issue by Axaressa** [KenediaDev/Kenedia.BlishHUD#25]
The OCR cannot read one of my character names no matter where I move the box or how big it is. The character name has no special characters and this isn't an issue on any other character (I have over 20 characters for reference). I have no idea how to fix it. Yes, best match does work, but I turned it off due to occasional logging onto the wrong character. I don't know if this can be fixed, but any input would be greatly appreciated!

![image](https://github.com/user-attachments/assets/77fbfbbd-e13c-4f6b-a9aa-de569b88d1d9)

**Comment by KenediaDev** [comment]
There're two number boxes on the bottom. You can adjust the right one until it works for that name. It also helps to move the box a bit to the right so you gave less spacing before the name. Just make sure the other names work too with the adjusted value.

Sadly the OCR is kinda tricky because I would need training data for the model based on GW2 which is something I haven't had the time to deep dive in. I hope to do it at some point if I have a little more than.

**Comment by Axaressa** [comment]
I've declared that this character is cursed as their name can only be read at specifically 237, nothing above or below, which is obviously way too high a value and messes with all the other character names. Thank you for the advice though!
